// TODO: WE NEED ONLY TO HANDLE TIME CHECK APP STATE AND LINK IT TO YOUR LOGIC:


// TODO: THE BULLET IS RANDOM AND NOT RELATED TO ALIVE INVADERS CHECK IT PLEASE YOU DID THE LOGIC BEHIND IT IT IS EASY FOR YOU TO KNOW THE SOURCE OF THE PROBLEM: